// lib/mock-invoices.ts
import { InvoiceFormData } from "@/schemas/invoice";

export const mockInvoices: InvoiceFormData[] = [
  {
    invoiceNumber: "INV-2025-001",
    clientName: "SARL Lumière Bleue",
    clientAddress: "123 Rue de la Paix, Antananarivo",
    dateIssued: "2025-07-01", // Changé la date pour une meilleure répartition
    dueDate: "2025-07-25",
    items: [
      { description: "Hébergement (2 nuits)", quantity: 2, unitPrice: 50000, total: 100000 },
      { description: "Petit-déjeuner", quantity: 2, unitPrice: 15000, total: 30000 },
    ],
    subTotal: 130000,
    taxRate: 20,
    taxAmount: 26000,
    totalAmount: 156000,
    paymentStatus: "En attente",
    paymentMethod: undefined,
    recordedBy: "Caissier A",
    notes: "Client fidèle, à contacter pour offre spéciale.",
  },
  {
    invoiceNumber: "INV-2025-002",
    clientName: "Mr. Jean Dupont",
    clientAddress: "45 Av. de la Liberté, Fianarantsoa",
    dateIssued: "2025-07-05",
    dueDate: "2025-07-05",
    items: [
      { description: "Repas du midi", quantity: 1, unitPrice: 25000, total: 25000 },
    ],
    subTotal: 25000,
    taxRate: 20,
    taxAmount: 5000,
    totalAmount: 30000,
    paymentStatus: "Payée",
    paymentMethod: "Espèces",
    recordedBy: "Caissier B",
    notes: "Paiement immédiat en espèces.",
  },
  {
    invoiceNumber: "INV-2025-003",
    clientName: "Agence Voyage Rapide",
    clientAddress: "789 Bd. de l'Indépendance, Toamasina",
    dateIssued: "2025-07-10",
    dueDate: "2025-08-15",
    items: [
      { description: "Location salle conférence (1 jour)", quantity: 1, unitPrice: 200000, total: 200000 },
      { description: "Boissons et snacks", quantity: 5, unitPrice: 10000, total: 50000 },
    ],
    subTotal: 250000,
    taxRate: 20,
    taxAmount: 50000,
    totalAmount: 300000,
    paymentStatus: "En attente",
    paymentMethod: undefined,
    recordedBy: "Caissier C",
    notes: "Facture pour événement d'entreprise.",
  },
  {
    invoiceNumber: "INV-2025-004",
    clientName: "Mme. Sophie Dubois",
    clientAddress: "10 Rue des Roses, Antananarivo",
    dateIssued: "2025-07-12",
    dueDate: "2025-07-12",
    items: [
      { description: "Consultation individuelle", quantity: 1, unitPrice: 80000, total: 80000 },
    ],
    subTotal: 80000,
    taxRate: 20,
    taxAmount: 16000,
    totalAmount: 96000,
    paymentStatus: "Payée",
    paymentMethod: "Carte Bancaire",
    recordedBy: "Caissier A",
    notes: "Rendez-vous de suivi.",
  },
  {
    invoiceNumber: "INV-2025-005",
    clientName: "Restaurant Le Goût",
    clientAddress: "22 Av. de l'Indépendance, Antsirabe",
    dateIssued: "2025-07-16",
    dueDate: "2025-07-30",
    items: [
      { description: "Fournitures de bureau", quantity: 10, unitPrice: 5000, total: 50000 },
      { description: "Maintenance informatique", quantity: 1, unitPrice: 100000, total: 100000 },
    ],
    subTotal: 150000,
    taxRate: 20,
    taxAmount: 30000,
    totalAmount: 180000,
    paymentStatus: "Partiellement payée",
    paymentMethod: undefined,
    recordedBy: "Caissier B",
    notes: "Attente du solde.",
  },
];